name: tagpr

on:
  push:
    branches:
      - main

jobs:
  tagpr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Run tagpr
        uses: Songmu/tagpr@v1
        env:
          # Use PAT if available, otherwise fallback to GITHUB_TOKEN
          # PAT is required to trigger the release workflow
          GITHUB_TOKEN: ${{ secrets.TAGPR_PAT || secrets.GITHUB_TOKEN }}